# Site settings
title: Toft and Toddy
email: cdr255@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A development blog for projects undertaken by Chris Rodriguez Productions,
  including video games, board games, music, writing, and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://toftandtoddy.com" # the base hostname & protocol for your site
twitter_username: cdr255
github_username:  cdr255

# Build settings
markdown: kramdown

highlighter: pygments